/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetOracle,
  IAssetOracleInterface,
} from "../../../contracts/SimpleDEX.sol/IAssetOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAssetOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetOracleInterface {
    return new Interface(_abi) as IAssetOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetOracle {
    return new Contract(address, _abi, runner) as unknown as IAssetOracle;
  }
}
