/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  AssetOracle,
  AssetOracleInterface,
} from "../../contracts/AssetOracle";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "PriceUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    name: "assetPrices",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "updatePrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b0319163317905561038a806100326000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80634a432a4614610051578063524f3889146100665780638da5cb5b1461008c578063f9172888146100b7575b600080fd5b61006461005f366004610257565b6100e2565b005b61007961007436600461029c565b61018c565b6040519081526020015b60405180910390f35b60005461009f906001600160a01b031681565b6040516001600160a01b039091168152602001610083565b6100796100c536600461029c565b805160208183018101805160018252928201919093012091525481565b6000546001600160a01b0316331461012c5760405162461bcd60e51b81526020600482015260096024820152682737ba1037bbb732b960b91b604482015260640160405180910390fd5b8060018360405161013d91906102fd565b9081526020016040518091039020819055507f159e83f4712ba2552e68be9d848e49bf6dd35c24f19564ffd523b6549450a2f48282604051610180929190610319565b60405180910390a15050565b600060018260405161019e91906102fd565b9081526020016040518091039020549050919050565b634e487b7160e01b600052604160045260246000fd5b600082601f8301126101db57600080fd5b813567ffffffffffffffff808211156101f6576101f66101b4565b604051601f8301601f19908116603f0116810190828211818310171561021e5761021e6101b4565b8160405283815286602085880101111561023757600080fd5b836020870160208301376000602085830101528094505050505092915050565b6000806040838503121561026a57600080fd5b823567ffffffffffffffff81111561028157600080fd5b61028d858286016101ca565b95602094909401359450505050565b6000602082840312156102ae57600080fd5b813567ffffffffffffffff8111156102c557600080fd5b6102d1848285016101ca565b949350505050565b60005b838110156102f45781810151838201526020016102dc565b50506000910152565b6000825161030f8184602087016102d9565b9190910192915050565b60408152600083518060408401526103388160608501602088016102d9565b602083019390935250601f91909101601f19160160600191905056fea264697066735822122097e37eb64990e625c5a6ea6d60b9c2e281f886c369cd9b2637597ce3efc84fc264736f6c63430008180033";

type AssetOracleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AssetOracleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AssetOracle__factory extends ContractFactory {
  constructor(...args: AssetOracleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AssetOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AssetOracle__factory {
    return super.connect(runner) as AssetOracle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AssetOracleInterface {
    return new Interface(_abi) as AssetOracleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AssetOracle {
    return new Contract(address, _abi, runner) as unknown as AssetOracle;
  }
}
