/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetNftSol from "./AssetNFT.sol";
export type { assetNftSol };
import type * as assetTokenSol from "./AssetToken.sol";
export type { assetTokenSol };
import type * as simpleDexSol from "./SimpleDEX.sol";
export type { simpleDexSol };
export type { AssetOracle } from "./AssetOracle";
export type { ComplianceRegistry } from "./ComplianceRegistry";
