/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetNFT } from "./AssetNFT";
export type { IComplianceRegistry } from "./IComplianceRegistry";
