
// This file is automatically generated by the deployment script
// However, since we are patching the system live, we define the structure here.
// The real values will be populated by the updated deploy script.

export interface ContractsConfig {
    complianceAddress: string;
    tokenAddress: string;
    oracleAddress: string;
    dexAddress: string;
    networkId: string;
}

export const ContractABIs = {
    // We will load these from the JSON files or hardcode minimal interfaces
    // For simplicity in this hotfix, we can use minimal human-readable ABIs
    ComplianceRegistry: [
        "function owner() external view returns (address)",
        "function addToWhitelist(address _account) external",
        "function removeFromWhitelist(address _account) external",
        "function isVerified(address _account) external view returns (bool)",
        "function addToBlacklist(address _account) external"
    ],
    AssetToken: [
        "function balanceOf(address account) external view returns (uint256)",
        "function approve(address spender, uint256 amount) external returns (bool)",
        "function transfer(address to, uint256 amount) external returns (bool)",
        "function allowance(address owner, address spender) external view returns (uint256)",
        "function symbol() external view returns (string)",
        "function decimals() external view returns (uint8)",
        "event Transfer(address indexed from, address indexed to, uint256 value)"
    ],
    AssetNFT: [
        "function owner() external view returns (address)",
        "function balanceOf(address account) external view returns (uint256)",
        "function ownerOf(uint256 tokenId) external view returns (address)",
        "function tokenURI(uint256 tokenId) external view returns (string)",
        "function transferFrom(address from, address to, uint256 tokenId) external",
        "function mintedURIs(string memory _uri) external view returns (bool)",
        "function nextTokenId() external view returns (uint256)",
        // Admin functions
        "function mint(address to, string memory _uri) external",
        "function transferOwnership(address newOwner) external",
        // Marketplace functions
        "function listForSale(uint256 tokenId, uint256 price) external",
        "function cancelListing(uint256 tokenId) external",
        "function buyNFT(uint256 tokenId) external payable",
        "function getListing(uint256 tokenId) external view returns (address seller, uint256 price, bool isActive)",
        // Events
        "event NFTListed(uint256 indexed tokenId, address indexed seller, uint256 price)",
        "event NFTSold(uint256 indexed tokenId, address indexed buyer, address indexed seller, uint256 price)",
        "event ListingCancelled(uint256 indexed tokenId)"
    ],
    SimpleDEX: [
        "function buyTokens() external payable",
        "function sellTokens(uint256 amount) external",
        "function price() external view returns (uint256)",
        "event TokenPurchased(address indexed buyer, uint256 amount)",
        "event TokenSold(address indexed seller, uint256 amount)"
    ],
    AssetOracle: [
        "function owner() external view returns (address)",
        "function updatePrice(string memory symbol, uint256 price) external",
        "function getPrice(string memory symbol) external view returns (uint256)",
        "event PriceUpdated(string symbol, uint256 price)"
    ]
};
